"""make target_year nullable

Revision ID: 039e74b62fbd
Revises: f3d3bfe9ab6b
Create Date: 2026-03-05 22:57:36.204999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '039e74b62fbd'
down_revision: Union[str, Sequence[str], None] = 'f3d3bfe9ab6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rounds', 'target_year',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rounds', 'target_year',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
