"""add unique constraint username per game

Revision ID: f3d3bfe9ab6b
Revises: 4e59088eb156
Create Date: 2026-03-05 19:38:19.366237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d3bfe9ab6b'
down_revision: Union[str, Sequence[str], None] = '4e59088eb156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_participant_game_username', 'participants', ['game_uuid', 'username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_participant_game_username', 'participants', type_='unique')
    # ### end Alembic commands ###
